# Generated by Django 5.2.12 on 2026-04-01 04:28

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('is_reservable', models.BooleanField(default=True)),
                ('table_type', models.CharField(db_column='type', max_length=64)),
                ('library_floor', models.IntegerField()),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Table',
            },
        ),
        migrations.CreateModel(
            name='WeightSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('last_reading_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'weight_sensor',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=64)),
                ('id_number', models.CharField(max_length=64)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('otp', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('overstay_alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(db_column='table_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.table')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='LCDDisplay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcd_type', models.CharField(db_column='type', max_length=64)),
                ('recorded_at', models.DateTimeField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('table', models.OneToOneField(blank=True, db_column='table_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lcd_display', to='api.table')),
            ],
            options={
                'db_table': 'LCD_Display',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='weight_sensor',
            field=models.ForeignKey(db_column='weight_sensor_id', on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='api.weightsensor'),
        ),
        migrations.CreateModel(
            name='OccupancyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField()),
                ('event_type', models.CharField(max_length=64)),
                ('weight_sensor', models.ForeignKey(db_column='weight_sensor_id', on_delete=django.db.models.deletion.CASCADE, related_name='occupancy_events', to='api.weightsensor')),
            ],
            options={
                'db_table': 'occupancy_event',
            },
        ),
    ]
