# Generated by GPT for table-only CRUD

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="weight_sensor",
            field=models.ForeignKey(
                blank=True,
                db_column="weight_sensor_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tables",
                to="api.weightsensor",
            ),
        ),
    ]

