# Generated by Django 5.2.12 on 2026-04-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weightsensor_location_to_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
